services:
  - type: web
    name: conversor-monedas
    env: go
    buildCommand: go mod tidy && go build -o conversor -buildvcs=false
    startCommand: ./conversor
    envVars:
      # No es necesario establecer PORT manualmente, Render lo asigna automáticamente
      - key: CACHE_TTL
        value: 5m
      - key: GO_VERSION
        value: 1.18
      - key: ENVIRONMENT
        value: production
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /api/v1/health
