services:
  - type: web
    name: conversor-monedas
    env: go
    buildCommand: go mod tidy && go build -o conversor
    startCommand: ./conversor
    envVars:
      - key: PORT
        value: 10000
      - key: CACHE_TTL
        value: 5
      - key: GO_VERSION
        value: 1.20
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /api/v1/health
