services:
  - type: web
    name: conversor-monedas
    env: go
    buildCommand: pip install -r requirements.txt && go mod tidy && go build -o conversor -buildvcs=false
    startCommand: ./conversor
    envVars:
      # Render inyecta automáticamente la variable PORT
      - key: CACHE_TTL
        value: 5m
      - key: GO_VERSION
        value: 1.18
      - key: ENVIRONMENT
        value: production
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 120  # Aumentar el timeout para dar tiempo a que la aplicación se inicie
